### ISSUE TITLE
Copy HTML button not working

### ISSUE THREAD

**Issue by ctorgalson** [markconroy/elements#1]
![image](https://user-images.githubusercontent.com/1063424/228168043-de47ff17-8ed3-4f83-9b5a-e0eeddc9fbe2.png)

One of two things needs to happen:

1. `divToCopy` in the js could be defined as `document.querySelector('main')`, or
2. a `<div/>` could be added as a direct child of `<main/>` with everything else inside it

**Comment by markconroy** [comment]
Hmmm, it was working on my local 🤣

**Comment by markconroy** [comment]
That should be fixed now @ctorgalson. Thanks for reporting.
